### ISSUE TITLE
Request params not being included in request

### ISSUE THREAD

**Issue by iAmWillShepherd** [OneSignal/onesignal-ruby-api#15]
It's unclear how to create a notification, and the docs don't help with accomplishing this task. In addition, the error messages aren't helpful to unblock devs who are stuck. Essentially, the error message leads the developer to think the issue is their fault when, in reality, the bug has little to do with what the user did.

```sh
╭─iamwill@kronos ~/code/@onesignalDevelopers/onesignal-ruby-sample ‹main●›
╰─$ bundle exec ruby app.rb

From: /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/api_client.rb @ line 51 :

    46:     #
    47:     # @return [Array<(Object, Integer, Hash)>] an array of 3 elements:
    48:     #   the data deserialized from response body (could be nil), response status code and response headers.
    49:     def call_api(http_method, path, opts = {})
    50:       request = build_request(http_method, path, opts)
 => 51:       binding.irb
    52:
    53:       response = request.run
    54:
    55:       if @config.debugging
    56:         @config.logger.debug "HTTP response body ~BEGIN~\n#{response.body}\n~END~\n"

irb(#<OneSignal::ApiClient:0x00000001005e88b8>):001:0> request
=>
#<Typhoeus::Request:0x000000010056a198
 @base_url="https://onesignal.com/api/v1/notifications",
 @options=
  {:method=>:post,
   :headers=>
    {"User-Agent"=>"OpenAPI-Generator/1.0.0/ruby",
     "Content-Type"=>"application/json",
     "Accept"=>"application/json",
     "OS-Usage-Data"=>"kind=sdk, name=onesignal-ruby, version=1.0.0",
     "Authorization"=>"Bearer token=\"ZDI1ZGU3MWEtOTVlZC00ZDU1LWJlM2QtMTQ1YjJhNmI4YTQ2\"",
     "Expect"=>""},
   :params=>{},
   :params_encoding=>nil,
   :timeout=>0,
   :ssl_verifypeer=>true,
   :ssl_verifyhost=>2,
   :sslcert=>nil,
   :sslkey=>nil,
   :verbose=>false,
   :body=>"{\"isIos\":true,\"app_id\":\"e94108a6-83a3-4293-8d69-e1d634877f4b\",\"contents\":{\"en\":\"English Message\"}}",
   :maxredirs=>50},
 @original_options=
  {:method=>:post,
   :headers=>
    {"Content-Type"=>"application/json",
     "User-Agent"=>"OpenAPI-Generator/1.0.0/ruby",
     "Accept"=>"application/json",
     "OS-Usage-Data"=>"kind=sdk, name=onesignal-ruby, version=1.0.0",
     "Authorization"=>"Bearer token=\"ZDI1ZGU3MWEtOTVlZC00ZDU1LWJlM2QtMTQ1YjJhNmI4YTQ2\""},
   :params=>{},
   :params_encoding=>nil,
   :timeout=>0,
   :ssl_verifypeer=>true,
   :ssl_verifyhost=>2,
   :sslcert=>nil,
   :sslkey=>nil,
   :verbose=>false,
   :body=>"{\"isIos\":true,\"app_id\":\"e94108a6-83a3-4293-8d69-e1d634877f4b\",\"contents\":{\"en\":\"English Message\"}}"}>
irb(#<OneSignal::ApiClient:0x00000001005e88b8>):002:0> continue
/Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/api_client.rb:2:in `call_api': undefined local variable or method `continue' for #<OneSignal::ApiClient:0x00000001005e88b8 @config=#<OneSignal::Configuration:0x00000001005ea258 @scheme="https", @host="onesignal.com", @base_path="/api/v1", @server_index=0, @server_operation_index={}, @server_variables={}, @server_operation_variables={}, @timeout=0, @client_side_validation=true, @verify_ssl=true, @verify_ssl_host=true, @params_encoding=nil, @cert_file=nil, @key_file=nil, @debugging=false, @inject_format=false, @force_ending_format=false, @logger=#<Logger:0x00000001005e9f88 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x00000001005e9d80 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00000001005e98d0 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @binmode=false, @mon_data=#<Monitor:0x00000001005e9740>, @mon_data_owner_object_id=1040>>, @app_key="ZDI1ZGU3MWEtOTVlZC00ZDU1LWJlM2QtMTQ1YjJhNmI4YTQ2">, @user_agent="OpenAPI-Generator/1.0.0/ruby", @default_headers={"Content-Type"=>"application/json", "User-Agent"=>"OpenAPI-Generator/1.0.0/ruby"}> (NameError)
Did you mean?  context
	from <internal:prelude>:5:in `irb'
	from /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/api_client.rb:51:in `call_api'
	from /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/api/default_api.rb:215:in `create_notification_with_http_info'
	from /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/api/default_api.rb:163:in `create_notification'
	from app.rb:21:in `<main>'
irb(#<OneSignal::ApiClient:0x00000001005e88b8>):003:0>
irb(#<OneSignal::ApiClient:0x00000001005e88b8>):004:0>
irb(#<OneSignal::ApiClient:0x00000001005e88b8>):005:0> next
/Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/api_client.rb: /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/api_client.rb:5: Can't escape from eval with next (SyntaxError)
```

I tried to play around with the param to see if I could it it to show up in the request
 
```ruby
require 'dotenv/load'
require 'time'
require 'onesignal'

rest_api_key = ENV['ONESIGNAL_REST_API_KEY']
app_id = ENV['ONESIGNAL_APP_ID']

# setup authorization
OneSignal.configure do |config|
  # Configure Bearer authorization: app_key
  config.app_key = rest_api_key
end

api_instance = OneSignal::DefaultApi.new

begin
  # Create notification
  notification = OneSignal::Notification.new({ app_id: app_id })
  notification.contents = OneSignal::StringMap.new({ "en": 'English Message' })
  notification.included_segments = ['Active Users']

  notification_response = api_instance.create_notification(notification)
  notification_id = notification_response.id
  p result
rescue OneSignal::ApiError => e
  # binding.irb
  puts "Error when calling DefaultApi->create_notification: #{e}"
end
```

☝🏾 I know this code is incorrect; I only did it to see what I had to do to get the `Active Users` segment in the request. If I follow the docs, the param isn't included in the request, and I get the error I mentioned in #10.

###### HTTP Request being made
```sh
From: /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/api_client.rb @ line 51 :

    46:     #
    47:     # @return [Array<(Object, Integer, Hash)>] an array of 3 elements:
    48:     #   the data deserialized from response body (could be nil), response status code and response headers.
    49:     def call_api(http_method, path, opts = {})
    50:       request = build_request(http_method, path, opts)
 => 51:       binding.irb
    52:
    53:       response = request.run
    54:
    55:       if @config.debugging
    56:         @config.logger.debug "HTTP response body ~BEGIN~\n#{response.body}\n~END~\n"

irb(#<OneSignal::ApiClient:0x00000001013a9290>):001:0> request
=>
#<Typhoeus::Request:0x000000010132a800
 @base_url="https://onesignal.com/api/v1/notifications",
 @options=
  {:method=>:post,
   :headers=>
    {"User-Agent"=>"OpenAPI-Generator/1.0.0/ruby",
     "Content-Type"=>"application/json",
     "Accept"=>"application/json",
     "OS-Usage-Data"=>"kind=sdk, name=onesignal-ruby, version=1.0.0",
     "Authorization"=>"Bearer token=\"ZDI1ZGU3MWEtOTVlZC00ZDU1LWJlM2QtMTQ1YjJhNmI4YTQ2\"",
     "Expect"=>""},
   :params=>{},
   :params_encoding=>nil,
   :timeout=>0,
   :ssl_verifypeer=>true,
   :ssl_verifyhost=>2,
   :sslcert=>nil,
   :sslkey=>nil,
   :verbose=>false,
   :body=>"{\"included_segments\":[\"Active Users\"],\"isIos\":true,\"app_id\":\"e94108a6-83a3-4293-8d69-e1d634877f4b\",\"contents\":{\"en\":\"English Message\"}}",
   :maxredirs=>50},
 @original_options=
  {:method=>:post,
   :headers=>
    {"Content-Type"=>"application/json",
     "User-Agent"=>"OpenAPI-Generator/1.0.0/ruby",
     "Accept"=>"application/json",
     "OS-Usage-Data"=>"kind=sdk, name=onesignal-ruby, version=1.0.0",
     "Authorization"=>"Bearer token=\"ZDI1ZGU3MWEtOTVlZC00ZDU1LWJlM2QtMTQ1YjJhNmI4YTQ2\""},
   :params=>{},
   :params_encoding=>nil,
   :timeout=>0,
   :ssl_verifypeer=>true,
   :ssl_verifyhost=>2,
   :sslcert=>nil,
   :sslkey=>nil,
   :verbose=>false,
   :body=>"{\"included_segments\":[\"Active Users\"],\"isIos\":true,\"app_id\":\"e94108a6-83a3-4293-8d69-e1d634877f4b\",\"contents\":{\"en\":\"English Message\"}}"}>
```

I also think there's a bug in the client in general as the parameters aren't making it into the request. 

###### Result of execution

```sh
╭─iamwill@kronos ~/code/@onesignalDevelopers/onesignal-ruby-sample ‹main●›
╰─$ bundle exec ruby app.rb
/Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/models/inline_response200.rb:203:in `const_get': uninitialized constant OneSignal::OneOfobjectarray (NameError)

        klass = OneSignal.const_get(type)
                         ^^^^^^^^^^
	from /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/models/inline_response200.rb:203:in `_deserialize'
	from /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/models/inline_response200.rb:158:in `block in build_from_hash'
	from /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/models/inline_response200.rb:148:in `each_pair'
	from /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/models/inline_response200.rb:148:in `build_from_hash'
	from /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/models/inline_response200.rb:140:in `build_from_hash'
	from /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/api_client.rb:281:in `convert_to_type'
	from /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/api_client.rb:241:in `deserialize'
	from /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/api_client.rb:73:in `call_api'
	from /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/api/default_api.rb:215:in `create_notification_with_http_info'
	from /Users/iamwill/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/onesignal-1.0.0.beta1/lib/onesignal/api/default_api.rb:163:in `create_notification'
	from app.rb:22:in `<main>'
```

**Comment by iAmWillShepherd** [comment]
This issue proves that #10 is indeed not resolved and should be re-opened until a PR fixing it gets merged to close it. 

cc/ @jmadler

**Comment by iAmWillShepherd** [comment]
I should also add that I paired with Graham, who was instrumental in helping uncover a lot of the behind-the-scenes details.
