### ISSUE TITLE
[Bug]: Ruby SDK does not support ios_interruption_level

### ISSUE THREAD

**Issue by msencenb** [OneSignal/onesignal-ruby-api#34]
### What happened?

Try to use the ios_interruption_level [property described here](https://documentation.onesignal.com/reference/push-channel-properties).

SDK throws an error when attempting to use it.

```ruby
`ios_interruption_level` is not a valid attribute in `OneSignal::Notification`
```

### Steps to reproduce?

```Markdown
1. Install 1.0.1 of library, the latest available on Ruby Gems
2. Attempt to use the create_notification method
```

### What did you expect to happen?

I expected the library to send a push with the ios_interruption_level I passed in.

### Relevant log output

```Shell
`ios_interruption_level` is not a valid attribute in `OneSignal::Notification`. Please check the name to make sure it's valid. List of attributes: [:included_segments, :excluded_segments, :last_session, :first_session, :session_count, :session_time, :amount_spent, :bought_sku, :tag, :language, :app_version, :location, :email, :country, :include_player_ids, :include_external_user_ids, :include_email_tokens, :include_phone_numbers, :include_ios_tokens, :include_wp_wns_uris, :include_amazon_reg_ids, :include_chrome_reg_ids, :include_chrome_web_reg_ids, :include_android_reg_ids, :id, :value, :aggregation, :is_ios, :is_android, :is_huawei, :is_any_web, :is_chrome_web, :is_firefox, :is_safari, :is_wp_wns, :is_adm, :is_chrome, :channel_for_external_user_ids, :app_id, :external_id, :contents, :headings, :subtitle, :data, :huawei_msg_type, :url, :web_url, :app_url, :ios_attachments, :template_id, :content_available, :mutable_content, :target_content_identifier, :big_picture, :huawei_big_picture, :adm_big_picture, :chrome_big_picture, :chrome_web_image, :buttons, :web_buttons, :ios_category, :android_channel_id, :huawei_channel_id, :existing_android_channel_id, :huawei_existing_channel_id, :android_background_layout, :small_icon, :huawei_small_icon, :large_icon, :huawei_large_icon, :adm_small_icon, :adm_large_icon, :chrome_web_icon, :chrome_web_badge, :firefox_icon, :chrome_icon, :ios_sound, :android_sound, :huawei_sound, :adm_sound, :wp_wns_sound, :android_led_color, :huawei_led_color, :android_accent_color, :huawei_accent_color, :android_visibility, :huawei_visibility, :ios_badge_type, :ios_badge_count, :collapse_id, :web_push_topic, :apns_alert, :send_after, :delayed_option, :delivery_time_of_day, :ttl, :priority, :apns_push_type_override, :throttle_rate_per_minute, :android_group, :android_group_message, :adm_group, :adm_group_message, :thread_id, :summary_arg, :summary_arg_count, :email_subject, :email_body, :email_from_name, :email_from_address, :sms_from, :sms_media_urls]
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/onesignal-1.0.1/lib/onesignal/models/notification.rb:653:in `block in initialize'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/onesignal-1.0.1/lib/onesignal/models/notification.rb:651:in `each'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/onesignal-1.0.1/lib/onesignal/models/notification.rb:651:in `each_with_object'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/onesignal-1.0.1/lib/onesignal/models/notification.rb:651:in `initialize'
/Users/msencenb/Development/wrestling/app/notifications/notification.rb:147:in `new'
/Users/msencenb/Development/wrestling/app/notifications/notification.rb:147:in `build_onesignal_notification'
/Users/msencenb/Development/wrestling/app/notifications/new_message_notification.rb:64:in `to_onesignal'
/Users/msencenb/Development/wrestling/app/notifications/notification.rb:88:in `to_push'
/Users/msencenb/Development/wrestling/app/notifications/notification.rb:67:in `send_push'
/Users/msencenb/Development/wrestling/app/notifications/notification.rb:32:in `block in deliver'
/Users/msencenb/Development/wrestling/app/notifications/notification.rb:24:in `each'
/Users/msencenb/Development/wrestling/app/notifications/notification.rb:24:in `deliver'
/Users/msencenb/Development/wrestling/app/jobs/notify_job.rb:13:in `perform'
/Users/msencenb/Development/wrestling/app/jobs/application_job.rb:23:in `block in perform_now'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/i18n-1.12.0/lib/i18n.rb:322:in `with_locale'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activejob-6.1.7/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activejob-6.1.7/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activejob-6.1.7/lib/active_job/instrumentation.rb:21:in `block in instrument'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/appsignal-3.3.3/lib/appsignal/hooks/active_support_notifications.rb:19:in `block in instrument'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/appsignal-3.3.3/lib/appsignal/hooks/active_support_notifications.rb:18:in `instrument'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activejob-6.1.7/lib/active_job/instrumentation.rb:31:in `instrument'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activejob-6.1.7/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activejob-6.1.7/lib/active_job/logging.rb:22:in `block in tag_logger'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:37:in `tagged'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:99:in `tagged'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activejob-6.1.7/lib/active_job/logging.rb:22:in `tag_logger'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activejob-6.1.7/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:137:in `run_callbacks'
/Users/msencenb/Development/wrestling/app/jobs/application_job.rb:22:in `perform_now'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activejob-6.1.7/lib/active_job/execution.rb:25:in `block in execute'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activejob-6.1.7/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/execution_wrapper.rb:91:in `wrap'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/reloader.rb:72:in `block in wrap'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/execution_wrapper.rb:91:in `wrap'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/reloader.rb:71:in `wrap'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activejob-6.1.7/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:137:in `run_callbacks'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activejob-6.1.7/lib/active_job/execution.rb:23:in `execute'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/appsignal-3.3.3/lib/appsignal/hooks/active_job.rb:40:in `execute'
/Users/msencenb/.rvm/gems/ruby-3.0.5@wrestling/gems/activejob-6.1.7/lib/active_job/queue_adapters/resque_adapter.rb:47:in `perform'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @msencenb, sorry this issue’s gone stale. This property was indeed previously missing from the SDK.

We have been working on a new major version 5.x.x that now includes the `ios_interruption_level` property. Please check out the latest release at [5.2.0-beta1](https://github.com/OneSignal/onesignal-ruby-api/releases/tag/v5.2.0-beta1).

Please reach out with any further questions or feedback.
